app/models.py
#from flask import url_for
from app import db




class Task(db.Model):

    task_id = db.Column(db.Integer, primary_key=True)
    task_title = db.Column(db.String(128))
    task_desc = db.Column(db.String(128), index=True)
    task_status = db.Column(db.String(128))
    task_date = db.Column(db.String(128))
    task_Cname = db.Column(db.String(128))
    task_address = db.Column(db.String(128))
    task_time = db.Column(db.String(128))
    task_duration = db.Column(db.String(128))

app/main/forms.py
# import flask_wtf
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectField, TextAreaField, DateField, TimeField, IntegerField, FloatField
from wtforms.validators import ValidationError, DataRequired, Length


class TaskForm(FlaskForm):
    task_title = StringField('Title', validators=[DataRequired()])
    task_desc = TextAreaField('Description', validators=[DataRequired()])
    task_status_completed = SelectField('Status', choices=[('todo', 'Todo'), ('doing', 'Doing'), ('done', 'Done')])
    task_time = StringField('Time', validators=[DataRequired()])
    task_location = StringField('Location', validators=[DataRequired()])
    task_CName = StringField('Customer', validators=[DataRequired()])
    task_duration = StringField('Duration', validators=[DataRequired()])
    task_date = ""
    submit = SubmitField('submit')

app.py
from app import create_app

app = create_app()

app/__init__.py
from flask import Flask, current_app

from config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_bootstrap import Bootstrap

## from flask_migrate  import Migrate
## from flask_login import LoginManager

# Instanciate modules used in the project.

db = SQLAlchemy()

## migrate = Migrate()
## login = LoginManager()


def create_app(config_class=Config):

    app = Flask(__name__)

    # load configuration parameters from Config class
    app.config.from_object(config_class)

    # Initialize app for db and migrate modules.
    db.init_app(app)
    bootstrap = Bootstrap(app)
    ##migrate.init_app(app,db)
    ##login.init_app(app)


    # Added the autho blueprint
    ##from app.auth import bp as auth_routes_bp
    ##app.register_blueprint(auth_routes_bp,url_prefix='/auth')


    # Added the main app.
    from app.main import bp as main_routes_bp
    app.register_blueprint(main_routes_bp)
    return app;

app/main/__init__.py
# Imports the Blueprint class from flask.
from flask import Blueprint

bp = Blueprint('main',__name__)

from app.main import routes

app/main/routes.py
from flask import render_template,  redirect, url_for, request
from app.main import bp
from app import db
from app.main.forms import TaskForm
from app.models import Task
from datetime import datetime

# Main route of the applicaitons.
@bp.route('/', methods=['GET','POST'])
def index():
    return render_template("main/index.html")


#
#  Route for viewing and adding new tasks.
@bp.route('/todolist/<int:sortby>/', methods=['GET','POST'])
def todolist(sortby):
    if sortby == 0:
        todo_list = Task.query.order_by(Task.task_title)
    elif sortby == 1:
        todo_list = Task.query.order_by(Task.task_desc)
    elif sortby == 2:
        todo_list = Task.query.order_by(Task.task_date)
    elif sortby == 3:
        todo_list = Task.query.order_by(Task.task_status)
    else:
        todo_list = Task.query.order_by(Task.task_id)

    date = datetime.now().date()
    for i in todo_list:
        task_date = datetime.strptime(i.task_date, "%Y-%m-%d").date()
        if task_date < date and i.task_status != "done":
            i.task_status = "overdue"


    return render_template("main/todolist.html",todo_list = todo_list)


#
# Route for removing a task
@bp.route('/todolist/remove/<int:task_id>', methods=['GET','POST'])
def remove_task(task_id):

    # Query database, remove items
    Task.query.filter(Task.task_id == task_id).delete()
    db.session.commit()

    return redirect(url_for('main.todolist', sortby=0))


#
# Route for editing a task

@bp.route('/todolist/edit/<int:task_id>', methods=['GET','POST'])
def edit_task(task_id):
    form = TaskForm()
    print(form.validate_on_submit())
    if form.validate_on_submit():
        # Get the data from the form, and add it to the database.

        current_task = Task.query.filter_by(task_id=task_id).first()
        current_task.task_title = form.task_title.data
        current_task.task_desc = form.task_desc.data
        current_task.task_date = request.form['date']
        current_task.task_status = form.task_status_completed.data
        current_task.task_duration = form.task_duration.data
        current_task.task_time = form.task_time.data
        current_task.task_location = form.task_location.data
        current_task.task_CName = form.task_CName.data
        db.session.commit()
        # After editing, redirect to the view page.
        return redirect(url_for('main.todolist', sortby=0))

    # get task for the database.
    current_task = Task.query.filter_by(task_id=task_id).first_or_404()

    # update the form model in order to populate the html form.
    form.task_title.data = current_task.task_title
    form.task_desc.data = current_task.task_desc
    form.task_status_completed.data = current_task.task_status
    form.task_date = current_task.task_date
    form.task_CName.data = current_task.task_Cname
    form.task_location.data = current_task.task_address
    form.task_time.data = current_task.task_time
    form.task_duration.data = current_task.task_duration

    return render_template("main/todolist_edit_view.html",form=form, task_id = task_id, sortby=0)


@bp.route('/new_todolist', methods=['GET','POST'])
def new_task():
    form = TaskForm()
    print(form.validate_on_submit())
    if form.validate_on_submit():
        # Get the data from the form, and add it to the database.
        new_task = Task()
        new_task.task_title = form.task_title.data
        new_task.task_desc = form.task_desc.data
        new_task.task_status = form.task_status_completed.data
        new_task.task_date = request.form['date']
        new_task.task_time = form.task_time.data
        new_task.task_duration = form.task_duration.data
        new_task.task_address = form.task_location.data
        new_task.task_Cname = form.task_CName.data
        db.session.add(new_task)
        db.session.commit()
        todo_list = db.session.query(Task).all()
        return redirect(url_for('main.todolist', todo_list=todo_list, sortby=0))
    return render_template("main/todolist_new.html", form=form)

app/templates/layout.html
{% extends "bootstrap/base.html" %}
{% block metas %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="Individual Project Template for CUS 1166">
  <meta name="author" content="Christoforos Christoforou">
{% endblock  %}

{% block title %}
  CUS 1166 - Individual or Group Project Template
{% endblock %}

{% block styles %}
{{super()}}


<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css">
{% endblock %}


{% block navbar %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">CUS1166 Project</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      {%  block menuitems %}

      {%  endblock menuitems%}
    </ul>
    </div>
</nav>
{% endblock %}

{% block content %}
    {% block main_content %}
    {% endblock main_content %}
      {% block footer %}
      <!-- Footer -->
      <footer class="page-footer font-small blue fixed-bottom">

        <!-- Copyright -->
        <div class="footer-copyright text-center py-3">© 2019 Copyright:
          <a href="https://www.researchgate.net/profile/Christoforos_Christoforou"> Template project for CUS1166 by Dr. Christoforos Christoforou</a>
        </div>
        <!-- Copyright -->

      </footer>
      <!-- Footer -->
      {% endblock footer %}
{% endblock content%}

app/templates/main/index.html
{% extends "menu.html" %}

{% block main_content %}
<div class="container">
  <div class="row">
    <div class="col-lg-12 text-center">
      <h1 class="mt-5">Individual Project for CUS1166 -</h1>
      <p class="lead">Get ready to showcase your Software Engineering Skills!</p>
      <ul class="list-unstyled">
        <li> Applying agile methodoloies in software development </li>
        <li>Realizing a full sprint implementing use-case  </li>
        <li> Using Flask, ORMs, Forms to implement new features </li>
      </ul>
    </div>
  </div>
</div>
{% endblock %}

app/templates/main/todolist.html
{% extends "menu.html" %}

{% block main_content %}


<div class="page-content page-container" id="page-content">
    <h4 class="card-title">CUS1166 - Todo List</h4>
    <div class="dropdown">
    <button class="dropbtn">Sort By</button>
     <div class="dropdown-content">
    <a href="/todolist/0/">Title</a>
    <a href="/todolist/1/">Description</a>
    <a href="/todolist/2/">Date</a>
    <a href="/todolist/3/">Completion Status</a>
  </div>
</div>
    </br><a class="add btn btn-primary font-weight-bold todo-list-add-btn", href="/new_todolist">Add a task</a>




                       <!-- Show current tasks if avaiblae -->
                        <link rel="stylesheet", type="text/css", href="{{url_for('static', filename='css/cus1166_custom.css')}}">





                             {% for task in todo_list %}
                                <div class="padding">
                                <div class="add-items d-flex">
                                 <div class="list-wrapper">
                                <div class="row container d-flex justify-content-center">
                                <div class="col-lg-12">
                                <div class="card px-3">
                                 <div class="card-body">


                                    <div class="task_item" id="task_item">
                                     <h4>{{task.task_title}}</h4>
                                        <h6 class="small">{{task.task_date}}</h6>
                                      <label class="form-check-label">
                                          {% if 'done' == task.task_status %}
                                            {{task.task_desc}} <br/><span class="badge badge-success">{{task.task_status}}</span>
                                          {% elif 'doing' == task.task_status %}
                                            {{task.task_desc}} <br/><span class="badge badge-warning">{{task.task_status}}</span>
                                          {% elif 'todo' == task.task_status %}
                                             {{task.task_desc}} <br/><span class="badge badge-danger">{{task.task_status}}</span>
                                          {% elif 'overdue' == task.task_status %}
                                             {{task.task_desc}} <br/><span class="badge badge-danger">{{task.task_status}}</span>
                                          {% endif %}
                                            <p>{{task.task_time}}</p>
                                            <p>{{task.task_duration}}</p>
                                            <p>{{task.task_location}}</p>
                                            <p>{{task.task_CName}}</p>

                                            <i class="input-helper"></i>
                                      </label>
                                    </div>
                                                                     {% if 'done' == task.task_status%}
                                    <li class="completed">
                                {% else %}
                                    <li>
                                {% endif %}
                                    <a href="{{url_for('main.edit_task',task_id=task.task_id)}}">
                                         <i class="fas fa-edit"></i>
                                    </a>
                                    <a href="{{url_for('main.remove_task',task_id=task.task_id)}}" class="remove"><i class="fas fa-times"></i></a>
                              </li>
                                 </div>
                                </div>
                                </div>
                                </div>
                        </div>
                    </div>
                    </div>
                    </div>
                    </div>
                             {% endfor %}



            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}

app/templates/main/todolist_edit_view.html
{% extends "menu.html" %}

{% block content %}
<div class="page-content page-container" id="page-content">
    <div class="padding">
        <div class="row container d-flex justify-content-center">
            <div class="col-lg-12">
                <div class="card px-3">
                    <div class="card-body">
                        <h4 class="card-title">CUS1166 - Todo List</h4>
                        <form method="POST" action="{{url_for('main.edit_task',task_id=task_id)}}" >
                            <div class="add-items d-flex">
                                <!-- csrf_token is required to validate the form -->
                                {{ form.csrf_token }}
                                {{form.task_title}}
                                {{ form.task_desc(class_='form-control todo-list-input', placeholder='What do you need to do today?')}}
                                {{form.task_time(class_='form-control todo-list-input',placeholder='What time does this task take place')}}
                                {{form.task_duration(class_='form-control todo-list-input',placeholder='How long will it take')}}
                                {{form.task_location(class_='form-control todo-list-input',placeholder='Where will this be taking place')}}
                                {{form.task_CName(class_='form-control todo-list-input',placeholder='who is the customer')}}
                                <input type="date", name="date", value={{form.task_date}}>
                                {{ form.task_status_completed }}
                                <button class="add btn btn-primary font-weight-bold todo-list-add-btn">Save Changes</button>
                       </div>
                     </form>
                   </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/main/todolist_new.html
{% extends "menu.html" %}

{% block main_content %}
<div class="page-content page-container" id="page-content">
    <div class="padding">
        <div class="row container d-flex justify-content-center">
            <div class="col-lg-12">
                <div class="card px-3">
                    <div class="card-body">
                        <h4 class="card-title">CUS1166 - New Task</h4>
                        <form method="POST" action="{{url_for('main.new_task')}}" >

                        <br class="add-items d-flex">
                            {{ form.csrf_token }}
                            {{form.task_title(class_='form-control todo-list-input', placeholder='The Title')}}
                            {{form.task_desc(class_='form-control todo-list-input', placeholder='What do you need to do today?')}}
                            {{form.task_time(class_='form-control todo-list-input', placeholder='What time does this task take place')}}
                            {{form.task_duration(class_='form-control todo-list-input', placeholder='How long will it take')}}
                            {{form.task_location(class_='form-control todo-list-input', placeholder='Where will this be taking place')}}
                            {{form.task_CName(class_='form-control todo-list-input', placeholder='who is the customer')}}
                            <input type="date", name="date"></br>
                            {{ form.task_status_completed }}
                        </br><button class="add btn btn-primary font-weight-bold todo-list-add-btn">Save Task</button>
                        </form>
                       </div>
                     </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/menu.html
{% extends "layout.html" %}
{%  block menuitems %}

<li class="nav-item active">
  <a class="nav-link" href="/">Home<span class="sr-only">(current)</span></a>
</li>
<li class="nav-item">
  <a class="nav-link" href="/todolist/0">Tasks</a>
</li>
{%  endblock %}